version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    environment:
      - VITE_BACKEND_URI=http://localhost:8080
      - PORT=9000
    ports:
      - "9000:9000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    environment:
      - DATASOURCE=jdbc:postgresql://database:5432/vlpms
      - DATASOURCE_USERNAME=postgres
      - DATASOURCE_PASSWORD=postgres
      - VES_URI=https://driver-vehicle-licensing.api.gov.uk/vehicle-enquiry/v1/vehicles
      - VES_KEY=place_key_here
      - ALLOWED_ORIGINS=http://localhost:9000/
      - PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  database:
    build:
      context: ./database
    environment:
      - POSTGRES_DB=vlpms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_INITDB_ARGS=--encoding=UTF8
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5