version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "9000:9000"

  database:
    image: postgres
    environment:
      - POSTGRES_DB=vlpms
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - internal

networks:
  internal:
    driver: bridge